
on: [push]
name: Flutter basics

env:
  flutter_version: "2.5.3"
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Cache Flutter dependencies
      uses: actions/cache@v2.1.6
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Install dependencies
      run: flutter pub get
    - name: Test
      run: flutter test
    - name: Build APK
      run: flutter build apk --debug --split-per-abi
    - name: Build Appbundle
      run: flutter build appbundle
