
on: [push]
name: Flutter basics

env:
  flutter_version: "2.5.3"
jobs:
  build:
    name: Test app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('**/pubspec.lock') }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Install dependencies
      run: flutter pub get
    - name: Test
      run: flutter test
